// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDefinition } from "./ModelDefinition";

/**
 * Response for GET /api/config
 */
export type AppConfig = { models: Array<ModelDefinition>, default_model: string, jira_configured: boolean, gitlab_configured: boolean, sessions_dir: string, repos_dir: string, base_prompt_path: string, };
