// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceType } from "./SourceType";

export type CreateSessionRequest = { source_type: SourceType, source_ref: string | null, title: string | null, model: string | null, custom_instructions: string | null, };
