// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLabMergeRequest = { iid: number, title: string, description: string | null, source_branch: string, web_url: string, state: string, };
