// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelDefinition = { 
/**
 * Full model identifier (e.g. "github-copilot/claude-sonnet-4.6")
 */
id: string, 
/**
 * Human-readable label (e.g. "Claude Sonnet 4.6")
 */
label: string, 
/**
 * Provider prefix (e.g. "github-copilot")
 */
provider: string, };
