// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionState } from "./SessionState";
import type { SourceType } from "./SourceType";

export type Session = { id: string, title: string, source_type: SourceType, source_ref: string | null, state: SessionState, opencode_port: number | null, opencode_session_id: string | null, opencode_path_prefix: string | null, workspace_path: string | null, model: string, custom_instructions: string | null, created_at: string, updated_at: string, };
